// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ9QApiaFCA6jKH-2Vo0gLXyPsSA1Rzv8',
    appId: '1:137333698519:web:e859cadf48f006da78e592',
    messagingSenderId: '137333698519',
    projectId: 'chat-3b77c',
    authDomain: 'chat-3b77c.firebaseapp.com',
    databaseURL: 'https://chat-3b77c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-3b77c.firebasestorage.app',
    measurementId: 'G-VG49SW0FL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn6jTpEWJxjJ5NUdDpxDGA9agFyEDXaV8',
    appId: '1:137333698519:android:2ca0671bdce47dc878e592',
    messagingSenderId: '137333698519',
    projectId: 'chat-3b77c',
    databaseURL: 'https://chat-3b77c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-3b77c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP1q_Hy0U9558_v59K3_WRLzyRFwBhaUg',
    appId: '1:137333698519:ios:8be93b81ea4b434278e592',
    messagingSenderId: '137333698519',
    projectId: 'chat-3b77c',
    databaseURL: 'https://chat-3b77c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-3b77c.firebasestorage.app',
    iosClientId: '137333698519-ihco0k47rrjbimuiqcshn6n595jer0ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP1q_Hy0U9558_v59K3_WRLzyRFwBhaUg',
    appId: '1:137333698519:ios:8be93b81ea4b434278e592',
    messagingSenderId: '137333698519',
    projectId: 'chat-3b77c',
    databaseURL: 'https://chat-3b77c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-3b77c.firebasestorage.app',
    iosClientId: '137333698519-ihco0k47rrjbimuiqcshn6n595jer0ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ9QApiaFCA6jKH-2Vo0gLXyPsSA1Rzv8',
    appId: '1:137333698519:web:9ea8ccd202e5b64a78e592',
    messagingSenderId: '137333698519',
    projectId: 'chat-3b77c',
    authDomain: 'chat-3b77c.firebaseapp.com',
    databaseURL: 'https://chat-3b77c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-3b77c.firebasestorage.app',
    measurementId: 'G-VSY138SE6W',
  );
}
